--- #YAML:1.0
name:                Config-YUM
version:             1.9
abstract:            Perl extension for parsing yum.conf
license:             ~
author:              
    - Oliver Falk <oliver@linux-kernel.at>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Config::IniHash:               0
    File::Remove:                  0
    File::Temp:                    0
    FreezeThaw:                    0
    Hash::Merge:                   0
    LWP::UserAgent:                0
    PerlIO::gzip:                  0
    RPM2:                          0
    Sort::Versions:                0
    XML::LibXML:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
